### PR TITLE
export astah diagrams data (such as flowchart, sequence chart ) to mermaid text fomat and Plantuml format

### PR DESCRIPTION
**Pull request by Avens666**
I add 4 js script file for astah  script plugin.
They could export astah diagrams data (such as flowchart, class chart ) to mermaid text fomat and Plantuml format

https://github.com/Avens666/Astah_Jude_UML_export_to_Markdown-mermaid-Plantuml-

### CODE REVIEW

**Comment by myamamoto** [comment]
@Avens666 I got some errors when I run these scripts. Don't you get any errors?
Thanks anyway!
And then, I am looking forward to PR for sample scripts output PlantUML format about Class Diagram,  State Machine Diagram.

**Comment by Avens666** [comment]
What error you get？ which script？  I test  script in some case，no error，but maybe complex diagrams could not convert.
for class diagram to plantuml，there a python tool named hpp2plantuml，could convert  h file to plantuml

**Comment by myamamoto** [comment]
@Avens666 I got such as a following error at all scripts.
ERROR: line = 59, column = -1
TypeError: flow_obj.indexOf is not a function in <eval> at line number 59

**Comment by Avens666** [comment]
@myamamoto  I use astah professional 6.8.0.  I just test in this version.
"TypeError: flow_obj.indexOf is not a function" is strange problem, I'm not meet it.  "indexOf" is java script Standard funtion 。
Could you send your problem diagram to me ,I'll check it.  [ cz_666@qq.com ]
you could ask my own repository to see usage.
https://github.com/Avens666/Astah_Jude_UML_export_to_Markdown-mermaid-Plantuml-

**Comment by myamamoto** [comment]
@Avens666 ​This error is due to the version of javascript engine.
The scripts needs to be improved for Nashorn. We will do the task.
By the way, instead of including them in script plugin.
we would like to publish the scripts you created on [the sample scripts page](https://astahblog.com/sample-scripts/
) with the link of your usage site. 
Is it OK? I am waiting for a good reply.

**Comment by Avens666** [comment]
It's Ok
No problem

**Comment by myamamoto** [comment]
We have improved scripts and published them on a web page.
https://astahblog.com/2017/10/02/export-to-plantuml-mermaid/

**Pull request closed without merging**
